apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: clusters.customer.upbound.io
spec:
  compositeTypeRef:
    apiVersion: customer.upbound.io/v1alpha1
    kind: Cluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: uchris-devex-democluster
    step: cluster
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
